### ISSUE TITLE
getUserByToken error

### ISSUE THREAD

**Issue by nilipta** [JEstebanDev/CRMGraphQL#1]
getUserByToken returns null.

![image](https://user-images.githubusercontent.com/29619564/216756466-cfd4a18b-6f3e-4ad7-8b74-77721be53b85.png)

**Comment by jtebaan** [comment]
Hey to get the data first of all go to AuthenticUser endpoint and paste this input variable 
{
  "input": {
    "email": "asd@asd.com",
    "password": "123"
  }
}
 After you get a token, put that token inside the headers Authorization for the other's operations... and that's it

I will put a custom error message later thank you
